language: python
python:
- 3.6
env:
- DJANGO_VERSION=1.11.4
install:
- pip install -q Django==$DJANGO_VERSION
- pip install -r requirements.txt
before_script:
- python3 manage.py makemigrations
- python3 manage.py migrate
script:
- python3 manage.py test
deploy:
  provider: heroku
  api_key:
    secure: CIQLjYQNShXFfyVt2GW/7ZOeEB35231O3HDyV2xarUJAjbbQlO3ubP/JJxsuSDK/X/rtpJUhcMCULBoGllOLegj787moLySVQDK0W7F3Q1Oz/Cna5zizXyHVrjwt/8InQPVjIFGY5P3zbbmvdwtVzxd2zFq7m7vF+YATTVoJWmbbcVnML/01YEx621KTtKdlLi1pdcpk93fu4Wx9WDutlCQQixi2dw5JZdWl35xbn4b2lL97qCaKsIDQm2cSkeqFvZznrvjkME4cChjqJd6HCOCArZfYmQkq8UaR8q0qV9jQ9Cfjzf3zmveqtIna+9gtqrwLbG20zH1K/nj5FF4JetcY2IGvT+Zcx86ZA+Bon/vsIs48eJgwOR8RrKE5rcHxmffE7Hmi204CUL+qBktOI0LVNTWCNe0psC30HeeeG3iMzgISx5HbTKyDjHimP9tawHuVpZnL0Pbitm1VbiwQngId3wRKQXLIyfcKubXrk9Zk1xVv9ReVx4n0MUXJ7WEaMi/90h5TNWsNw769KGc2INBnpBJQg7e5QjO74+KnPa2TpsViQmMwJobrCVbO6ox/ElgipW2q50pwNjGXKnGzOFpNpeGm9wE4QFv3mIEDZXEJHEK0vxVEq0KsvCY+HO270QVZcY/mJh1NWdfiIfCcWSSzQNgz3TB6/QRpM9Xe6V8=
  app: gcs01-breno-mariz-travis
